### ISSUE TITLE
コメント書く

### ISSUE THREAD

**Issue by r-i0** [r-i0/minishell#19]
ファイルごと、場合によっては関数ごとにコメント書く
コメントの形式は
```
/*
** 説明
*/
```
これで統一したいと思ってます
関数ごとに書くのはめんどくさそうなので基本はファイルごとで、説明が必要そうな関数、重要な関数はその上に
```
/*
** param (int param1)引数の説明
** param (int param2)引数の説明
** return 戻り値の説明
** 関数の説明
*/
```
みたいな感じで書きたいと思います

**Comment by ryojiroakiyama** [comment]
> ファイルごと、場合によっては関数ごとにコメント書く
> コメントの形式は
> 
> ```
> /*
> ** file name
> ** description
> */
> ```
> 
> これで統一したいと思ってます
> 関数ごとに書くのはめんどくさそうなので基本はファイルごとで、説明が必要そうな関数、重要な関数はその上に
> 
> ```
> /*
> ** param (int param1)引数の説明
> ** param (int param2)引数の説明
> ** return 戻り値の説明
> ** 関数の説明
> */
> ```
> 
> みたいな感じで書きたいと思います

**Comment by ryojiroakiyama** [comment]
> > ファイルごと、場合によっては関数ごとにコメント書く
> > コメントの形式は
> > ```
> > /*
> > ** file name
> > ** description
> > */
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > これで統一したいと思ってます
> > 関数ごとに書くのはめんどくさそうなので基本はファイルごとで、説明が必要そうな関数、重要な関数はその上に
> > ```
> > /*
> > ** param (int param1)引数の説明
> > ** param (int param2)引数の説明
> > ** return 戻り値の説明
> > ** 関数の説明
> > */
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > みたいな感じで書きたいと思います

**Comment by ryojiroakiyama** [comment]
僕もそのようにします〜。

**Comment by r-i0** [comment]
了解でっす
