### ISSUE TITLE
in_fdとout_fdの削除

### ISSUE THREAD

**Issue by r-i0** [r-i0/minishell#25]
# minishell.h内のin_fdとout_fdを削除する

@ryojiroakiyama 
自分の方で消しちゃって大丈夫ですか？あきやまさんのファイルの方はもう消したんでしたっけ。

**Comment by ryojiroakiyama** [comment]
@r-i0 僕の方は消したので(minishell.hも含め)消しちゃって大丈夫です！

**Comment by r-i0** [comment]
了解です。

**Comment by r-i0** [comment]
#27
