### ISSUE TITLE
catバグる

### ISSUE THREAD

**Issue by r-i0** [r-i0/minishell#35]
```
$ cat outfile
```
の場合、

```
cmdlist[0] "cat"
cmdlist[1] "outfile"
cmdlist[2] ""
```
になってる。
原因不明。

**Comment by r-i0** [comment]
@ryojiroakiyama 
たぶん自分のせいでした。原因はまだ分からないけど。

**Comment by ryojiroakiyama** [comment]
了解です！お願いします！

**Comment by r-i0** [comment]
おそらくなんですが、tabキーで候補を補完したときに、文字列の末尾にタブかスペースが入っているのが原因かと思われます。
tabキーを使わず引数を入力すると正常に動作しました。
cat 以外のコマンドでも、コマンド入力の後ろにスペースを入力するとそれが一つの引数と認識されているみたいなので修正します。

**Comment by r-i0** [comment]
@ryojiroakiyama 
ついでに、catしたときにabortになったりサニタイザーに怒られたりするのも同じところに原因がありました。

**Comment by ryojiroakiyama** [comment]
@r-i0 
なるほどです！
見つけづらいエラーありがとうございます、、笑
readlineが勝手にスペースを入れたりしてしまうってことですかね？
